//! Writing a translation out as Rust.
//!
//! Each segment becomes a module: a dispatcher over its block starts and one
//! small function per block, every line annotated with the original instruction.
//! The code relies on the including crate's `prelude`: the machine types, `Game`,
//! `Next`, `Stop`, and the control-transfer helpers.

use std::fmt::Write as _;

use machine::{Cond, Flag, Reg8, Reg16, Width};
use patches::Action;

use crate::Instruction;
use crate::ir::{Ir, LoopKind, MemRef, Operand};
use crate::translation::{Segment, Translation, ends_block};

/// A generated source file.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct File {
    /// File name, relative to the output directory.
    pub name: String,
    /// Rust source.
    pub contents: String,
}

/// Writes `translation` as Rust: `translated.rs` and one file per segment.
/// `origin` names the source in the header, e.g. the executable's SHA-256.
pub fn emit(translation: &Translation, origin: &str) -> Vec<File> {
    let mut files = vec![top(translation, origin)];
    files.extend(translation.segments.values().map(|segment| File {
        name: format!("segment_{:04x}.rs", segment.number),
        contents: segment_source(segment, origin),
    }));
    files
}

fn header(origin: &str) -> String {
    format!("// Generated by the translate crate from LDM.EXE ({origin}). Do not edit.\n")
}

fn top(translation: &Translation, origin: &str) -> File {
    let mut s = header(origin);
    for number in translation.segments.keys() {
        let _ = writeln!(
            s,
            "pub(crate) mod segment_{number:04x} {{\n    use super::prelude::*;\n    \
             include!(concat!(env!(\"OUT_DIR\"), \"/segment_{number:04x}.rs\"));\n}}"
        );
    }
    s.push_str(
        "\n/// Runs translated code from CS:IP until it yields: one translated step.\n\
         pub(crate) fn step(m: &mut Machine, g: &mut Game) -> Result<(), Stop> {\n    \
         m.steps += 1;\n    match m.regs.cs.wrapping_sub(LOAD_SEGMENT) {\n",
    );
    for number in translation.segments.keys() {
        let _ = writeln!(s, "        {number:#06x} => segment_{number:04x}::run(m, g),");
    }
    s.push_str(
        "        segment => Err(Stop::Unrecovered(Address::new(segment, m.regs.ip))),\n    }\n}\n",
    );
    File { name: "translated.rs".to_owned(), contents: s }
}

fn segment_source(segment: &Segment, origin: &str) -> String {
    let number = segment.number;
    let mut s = header(origin);
    s.push_str(
        "\n/// Runs blocks of this segment until one yields.\n\
         pub(crate) fn run(m: &mut Machine, g: &mut Game) -> Result<(), Stop> {\n    loop {\n        \
         let next = match m.regs.ip {\n",
    );
    let blocks = blocks(segment);
    for block in &blocks {
        let start = block[0].address.offset;
        let _ = writeln!(s, "            {start:#06x} => b{start:04x}(m, g)?,");
    }
    let _ = write!(
        s,
        "            ip => return Err(Stop::Unrecovered(Address::new({number:#06x}, ip))),\n        \
         }};\n        match next {{\n            Next::Goto(ip) => m.regs.ip = ip,\n            \
         Next::Yield => return Ok(()),\n        }}\n    }}\n}}\n"
    );
    for block in &blocks {
        s.push('\n');
        s.push_str(&block_source(segment, block));
    }
    s
}

/// Splits a segment into runs of instructions from each block start.
fn blocks(segment: &Segment) -> Vec<Vec<&Instruction>> {
    let mut blocks: Vec<Vec<&Instruction>> = Vec::new();
    let mut open = false;
    for (offset, instruction) in &segment.instructions {
        let continues =
            open && !segment.block_starts.contains(offset)
                && blocks.last().and_then(|block| block.last()).is_some_and(|previous| {
                    previous.next() == *offset && !ends_run(segment, previous)
                });
        if continues {
            blocks.last_mut().expect("an open block").push(instruction);
        } else {
            blocks.push(vec![instruction]);
        }
        open = true;
    }
    blocks
}

/// Whether the run of straight-line code stops after this instruction. A
/// replaced instruction never does: its hook may skip it.
fn ends_run(segment: &Segment, instruction: &Instruction) -> bool {
    ends_block(&instruction.ir) && !segment.replaced(instruction.address.offset)
}

fn block_source(segment: &Segment, block: &[&Instruction]) -> String {
    let start = block[0].address;
    let mut s = format!(
        "/// {start}\nfn b{:04x}(m: &mut Machine, g: &mut Game) -> Result<Next, Stop> {{\n",
        start.offset
    );
    for instruction in block {
        let _ = writeln!(s, "    // {:04x}  {}", instruction.address.offset, instruction.text);
        for line in with_patches(segment, instruction) {
            let _ = writeln!(s, "    {line}");
        }
    }
    let last = block[block.len() - 1];
    if !ends_run(segment, last) {
        let _ = writeln!(
            s,
            "    {}",
            continue_at(segment, last.next()).trim_start_matches("return ").trim_end_matches(';')
        );
    }
    s.push_str("}\n");
    s
}

fn with_patches(segment: &Segment, instruction: &Instruction) -> Vec<String> {
    let at = instruction.address;
    let next = instruction.next();
    let Some(patches) = segment.patches.get(&at.offset) else {
        return statements(segment, instruction);
    };
    let mut lines = vec![format!("m.regs.ip = {:#06x};", at.offset)];
    for patch in patches {
        match patch.action {
            Action::Before(hook) => lines.push(format!(
                "if let Some(next) = before(m, g, Hook::{hook:?}, {next:#06x})? {{ return Ok(next); }}"
            )),
            Action::Replace(hook) => {
                lines.push(format!("match replace(m, g, Hook::{hook:?}, {next:#06x})? {{"));
                lines.push("    Replaced::Original => {".to_owned());
                lines.extend(statements(segment, instruction).into_iter().map(|line| format!("        {line}")));
                lines.push("    }".to_owned());
                lines.push("    Replaced::Done => {}".to_owned());
                lines.push("    Replaced::Transfer(next) => return Ok(next),".to_owned());
                lines.push("}".to_owned());
                return lines;
            }
        }
    }
    lines.extend(statements(segment, instruction));
    lines
}

/// Continue at `target` after a jump: backward jumps yield, forward jumps to
/// recovered code continue in this segment, anything else yields there.
fn jump_to(segment: &Segment, from: u16, target: u16) -> String {
    if target <= from {
        format!("return yield_at(m, {target:#06x});")
    } else {
        continue_at(segment, target)
    }
}

/// Continue at `target` without yielding when it is recovered code.
fn continue_at(segment: &Segment, target: u16) -> String {
    if segment.instructions.contains_key(&target) {
        format!("return Ok(Next::Goto({target:#06x}));")
    } else {
        format!("return yield_at(m, {target:#06x});")
    }
}

fn register(register: Reg16) -> &'static str {
    match register {
        Reg16::Ax => "ax",
        Reg16::Cx => "cx",
        Reg16::Dx => "dx",
        Reg16::Bx => "bx",
        Reg16::Sp => "sp",
        Reg16::Bp => "bp",
        Reg16::Si => "si",
        Reg16::Di => "di",
        Reg16::Es => "es",
        Reg16::Cs => "cs",
        Reg16::Ss => "ss",
        Reg16::Ds => "ds",
    }
}

fn byte_register(register: Reg8) -> &'static str {
    match register {
        Reg8::Al => "al",
        Reg8::Cl => "cl",
        Reg8::Dl => "dl",
        Reg8::Bl => "bl",
        Reg8::Ah => "ah",
        Reg8::Ch => "ch",
        Reg8::Dh => "dh",
        Reg8::Bh => "bh",
    }
}

fn segment_of(mem: MemRef) -> String {
    format!("m.regs.{}", register(mem.segment))
}

fn offset_of(mem: MemRef) -> String {
    let registers: Vec<String> = [mem.base, mem.index]
        .into_iter()
        .flatten()
        .map(|r| format!("m.regs.{}", register(r)))
        .collect();
    let Some((first, rest)) = registers.split_first() else {
        return format!("{:#06x}", mem.displacement);
    };
    let mut expression = first.clone();
    for term in rest {
        let _ = write!(expression, ".wrapping_add({term})");
    }
    if mem.displacement != 0 {
        let _ = write!(expression, ".wrapping_add({:#06x})", mem.displacement);
    }
    expression
}

/// A 16-bit expression for an operand's value; bytes are zero-extended.
fn read(operand: Operand) -> String {
    match operand {
        Operand::Reg(r) => format!("m.regs.{}", register(r)),
        Operand::Reg8(r) => format!("u16::from(m.regs.{}())", byte_register(r)),
        Operand::Imm(value) => format!("{value:#06x}"),
        Operand::Mem(mem) => match mem.width {
            Width::Word => format!("m.memory.read16({}, {})", segment_of(mem), offset_of(mem)),
            Width::Byte => {
                format!("u16::from(m.memory.read8({}, {}))", segment_of(mem), offset_of(mem))
            }
        },
    }
}

/// An 8-bit expression for a byte operand's value.
fn read8(operand: Operand) -> String {
    match operand {
        Operand::Reg8(r) => format!("m.regs.{}()", byte_register(r)),
        Operand::Imm(value) => format!("{:#04x}", value & 0xff),
        Operand::Mem(mem) => format!("m.memory.read8({}, {})", segment_of(mem), offset_of(mem)),
        Operand::Reg(_) => format!("{} as u8", read(operand)),
    }
}

/// A statement storing a 16-bit `value` (truncated for bytes).
fn write(operand: Operand, value: &str) -> String {
    match operand {
        Operand::Reg(r) => format!("m.regs.{} = {value};", register(r)),
        Operand::Reg8(r) => format!("m.regs.set_{}({value} as u8);", byte_register(r)),
        Operand::Imm(_) => unreachable!("lowering never writes to an immediate"),
        Operand::Mem(mem) => match mem.width {
            Width::Word => {
                format!("m.memory.write16({}, {}, {value});", segment_of(mem), offset_of(mem))
            }
            Width::Byte => {
                format!("m.memory.write8({}, {}, {value} as u8);", segment_of(mem), offset_of(mem))
            }
        },
    }
}

fn width(width: Width) -> &'static str {
    match width {
        Width::Byte => "Width::Byte",
        Width::Word => "Width::Word",
    }
}

/// `let value = expression;` and the store, or one assignment for a register.
fn assign(dst: Operand, expression: &str) -> Vec<String> {
    match dst {
        Operand::Reg(_) => vec![write(dst, expression)],
        _ => vec![format!("let value = {expression};"), write(dst, "value")],
    }
}

fn condition(cond: Cond) -> String {
    format!("m.condition(Cond::{cond:?})")
}

fn flag(flag: Flag) -> String {
    format!("Flag::{flag:?}")
}

#[allow(clippy::too_many_lines, reason = "one arm per IR variant reads best as a table")]
fn statements(segment: &Segment, instruction: &Instruction) -> Vec<String> {
    let at = instruction.address;
    let (ip, next) = (at.offset, instruction.next());
    match &instruction.ir {
        Ir::Move { dst, src, width: Width::Byte } => match dst {
            Operand::Reg8(r) => vec![format!("m.regs.set_{}({});", byte_register(*r), read8(*src))],
            _ => vec![write(*dst, &read(*src))],
        },
        Ir::Move { dst, src, .. } => vec![write(*dst, &read(*src))],
        Ir::Alu { op, dst, src, width: w } => assign(
            *dst,
            &format!("m.alu(AluOp::{op:?}, {}, {}, {})", read(*dst), read(*src), width(*w)),
        ),
        Ir::Compare { op, a, b, width: w } => {
            vec![format!("m.alu(AluOp::{op:?}, {}, {}, {});", read(*a), read(*b), width(*w))]
        }
        Ir::Increment { dst, width: w } => {
            assign(*dst, &format!("m.alu(AluOp::Inc, {}, 1, {})", read(*dst), width(*w)))
        }
        Ir::Decrement { dst, width: w } => {
            assign(*dst, &format!("m.alu(AluOp::Dec, {}, 1, {})", read(*dst), width(*w)))
        }
        Ir::Negate { dst, width: w } => {
            assign(*dst, &format!("m.alu(AluOp::Neg, 0, {}, {})", read(*dst), width(*w)))
        }
        Ir::Not { dst, .. } => assign(*dst, &format!("!{}", read(*dst))),
        Ir::Shift { op, dst, count, width: w } => assign(
            *dst,
            &format!("m.shift(ShiftOp::{op:?}, {}, {}, {})", read(*dst), read(*count), width(*w)),
        ),
        Ir::Push(src) => vec![format!("m.push({});", read(*src))],
        Ir::Pop(dst) => assign(*dst, "m.pop()"),
        Ir::PushFlags => vec!["m.push(m.regs.flags | RESERVED);".to_owned()],
        Ir::PopFlags => vec!["m.regs.flags = m.pop() | RESERVED;".to_owned()],
        Ir::Exchange { a, b, .. } => vec![
            format!("let first = {};", read(*a)),
            format!("let second = {};", read(*b)),
            write(*a, "second"),
            write(*b, "first"),
        ],
        Ir::LoadAddress { dst, address } => {
            vec![format!("m.regs.{} = {};", register(*dst), offset_of(*address))]
        }
        Ir::LoadFarPointer { dst, segment: target, address } => vec![
            format!("let at = {};", offset_of(*address)),
            format!("let offset = m.memory.read16({}, at);", segment_of(*address)),
            format!("let segment = m.memory.read16({}, at.wrapping_add(2));", segment_of(*address)),
            format!("m.regs.{} = offset;", register(*dst)),
            format!("m.regs.{} = segment;", register(*target)),
        ],
        Ir::ConvertByteToWord => {
            vec!["m.regs.ax = i16::from(m.regs.al() as i8) as u16;".to_owned()]
        }
        Ir::ConvertWordToDouble => {
            vec!["m.regs.dx = if m.regs.ax & 0x8000 == 0 { 0 } else { 0xffff };".to_owned()]
        }
        Ir::Multiply { src, width: w, signed } => {
            vec![format!("m.multiply({}, {}, {signed});", read(*src), width(*w))]
        }
        Ir::Divide { src, width: w, signed } => vec![format!(
            "m.divide({}, {}, {signed}).at({:#06x}, {ip:#06x})?;",
            read(*src),
            width(*w),
            at.segment
        )],
        Ir::Jump { cond: None, target } => vec![jump_to(segment, ip, *target)],
        Ir::Jump { cond: Some(cond), target } => {
            vec![format!("if {} {{ {} }}", condition(*cond), jump_to(segment, ip, *target))]
        }
        Ir::JumpIndirect(target) => {
            vec![format!("m.regs.ip = {};", read(*target)), "return Ok(Next::Yield);".to_owned()]
        }
        Ir::Loop { kind, target } => {
            let test = match kind {
                LoopKind::Always => "m.regs.cx != 0".to_owned(),
                LoopKind::WhileEqual => format!("m.regs.cx != 0 && m.flag({})", flag(Flag::Zero)),
                LoopKind::WhileNotEqual => {
                    format!("m.regs.cx != 0 && !m.flag({})", flag(Flag::Zero))
                }
            };
            vec![
                "m.regs.cx = m.regs.cx.wrapping_sub(1);".to_owned(),
                format!("if {test} {{ {} }}", jump_to(segment, ip, *target)),
            ]
        }
        Ir::Call(target) => vec![format!("return call(m, {}, {next:#06x});", read(*target))],
        Ir::FarJump(target) => {
            vec![format!(
                "return far_jump(m, Address::new({:#06x}, {:#06x}));",
                target.segment, target.offset
            )]
        }
        Ir::FarJumpIndirect(pointer) => {
            vec![format!(
                "return far_jump_indirect(m, {}, {});",
                segment_of(*pointer),
                offset_of(*pointer)
            )]
        }
        Ir::FarCall(target) => vec![format!(
            "return far_call(m, Address::new({:#06x}, {:#06x}), {next:#06x});",
            target.segment, target.offset
        )],
        Ir::FarCallIndirect(pointer) => vec![format!(
            "return far_call_indirect(m, {}, {}, {next:#06x});",
            segment_of(*pointer),
            offset_of(*pointer)
        )],
        Ir::Return { release } => vec![format!("return ret(m, {release});")],
        Ir::ReturnFar { release } => vec![format!("return retf(m, {release});")],
        Ir::ReturnFromInterrupt => vec!["return iret(m);".to_owned()],
        Ir::Interrupt(number) => vec![
            format!("m.regs.ip = {ip:#06x};"),
            format!("if interrupt(m, g, {number:#04x})? {{ return Ok(Next::Yield); }}"),
        ],
        Ir::In { dst, port, width: w } => {
            assign(*dst, &format!("m.port_in({}, {})", read(*port), width(*w)))
        }
        Ir::Out { port, src, width: w } => {
            vec![format!("m.port_out({}, {}, {});", read(*port), read(*src), width(*w))]
        }
        Ir::SetFlag { flag: f, on } => vec![format!("m.set_flag({}, {on});", flag(*f))],
        Ir::ComplementCarry => vec!["m.set_flag(Flag::Carry, !m.flag(Flag::Carry));".to_owned()],
        Ir::LoadAhFromFlags => {
            vec![
                "m.regs.ax = (m.regs.ax & 0x00ff) | (((m.regs.flags & 0xd5) | RESERVED) << 8);"
                    .to_owned(),
            ]
        }
        Ir::StoreAhIntoFlags => vec![
            "m.regs.flags = (m.regs.flags & !0xd5) | ((m.regs.ax >> 8) & 0xd5) | RESERVED;"
                .to_owned(),
        ],
        Ir::Translate => vec![
            "let at = m.regs.bx.wrapping_add(u16::from(m.regs.al()));".to_owned(),
            "m.regs.set_al(m.memory.read8(m.regs.ds, at));".to_owned(),
        ],
        Ir::String { op, width: w, repeat, source } => vec![format!(
            "m.string_op(StringOp::{op:?}, {}, Repeat::{repeat:?}, m.regs.{});",
            width(*w),
            register(*source)
        )],
        Ir::Nop => Vec::new(),
    }
}
