#!/usr/bin/env python3
"""Bake the settings menu's font: build-time Pillow only, no runtime font engine.

Writes resources/ui-font.bmp, the glyph table in crates/desktop/src/font/glyphs.rs
and resources/ui-font.json. Usage: tools/bake_font.py /path/to/DejaVuSans.ttf
"""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[1]
PIXEL_SIZE = 88
ATLAS = 1024
ROW = 110


def rust_table(glyphs):
    """The glyph table as crates/desktop/src/font/glyphs.rs holds it."""
    lines = []
    for char, x, y, width, height, left, top, advance in glyphs:
        name = {' ': 'space', '\\': 'backslash'}.get(char, char)
        lines.append(f'    Glyph {{ x: {x}, y: {y}, w: {width}, h: {height}, left: {left}, '
                     f'top: {top}, advance: {advance:.4f} }}, // {name}')
    return ('// Generated by tools/bake_font.py from DejaVu Sans. See resources/FONT-LICENSE.txt.\n\n'
            'use super::Glyph;\n\n'
            "/// The printable ASCII characters' glyphs, from space to tilde.\n"
            'pub static GLYPHS: [Glyph; 95] = [\n' + '\n'.join(lines) + '\n];\n')


def bake(font_path):
    """Draw the printable ASCII characters into one atlas; return their glyphs."""
    from PIL import Image, ImageDraw, ImageFont
    font = ImageFont.truetype(str(font_path), PIXEL_SIZE)
    atlas = Image.new('RGBA', (ATLAS, ATLAS), (255, 255, 255, 0))
    draw = ImageDraw.Draw(atlas)
    glyphs, x, y = [], 2, 2
    for code in range(32, 127):
        char = chr(code)
        advance = font.getlength(char)
        left, top, right, bottom = font.getbbox(char, anchor='ls')
        width, height = max(1, right - left), max(1, bottom - top)
        if x + width + 2 > ATLAS:
            x, y = 2, y + ROW
        if y + height + 2 > ATLAS:
            raise ValueError('Font atlas too small')
        draw.text((x - left, y - top), char, font=font, fill=(255, 255, 255, 255), anchor='ls')
        glyphs.append((char, x, y, width, height, left, top, advance))
        x += width + 3
    png = ROOT / 'resources/ui-font.png'
    atlas.save(png)
    # ImageMagick writes BMP with a V4 alpha mask, which SDL_LoadBMP reads.
    subprocess.run(['magick', str(png), '-define', 'bmp:format=bmp4',
                    str(ROOT / 'resources/ui-font.bmp')], check=True)
    png.unlink()
    return glyphs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('font', type=Path)
    args = parser.parse_args()
    glyphs = bake(args.font)
    (ROOT / 'crates/desktop/src/font/glyphs.rs').write_text(rust_table(glyphs))
    manifest = {'font': args.font.name, 'sha256': hashlib.sha256(args.font.read_bytes()).hexdigest(),
                'pixel_size': PIXEL_SIZE, 'license': 'FONT-LICENSE.txt'}
    (ROOT / 'resources/ui-font.json').write_text(json.dumps(manifest, indent=2) + '\n')


if __name__ == '__main__':
    main()
