#!/usr/bin/env python3
"""Bake the bundled settings font; build-time Pillow only, no runtime font engine."""
from pathlib import Path
import argparse, hashlib, json
from PIL import Image, ImageDraw, ImageFont

p=argparse.ArgumentParser(description=__doc__)
p.add_argument('font',type=Path)
args=p.parse_args()
root=Path(__file__).resolve().parents[1]
font=ImageFont.truetype(str(args.font),88)
atlas=Image.new('RGBA',(1024,1024),(255,255,255,0))
draw=ImageDraw.Draw(atlas)
glyphs=[];x=y=2;row=110
for code in range(32,127):
    char=chr(code);advance=font.getlength(char)
    left,top,right,bottom=font.getbbox(char,anchor='ls')
    width=max(1,right-left);height=max(1,bottom-top)
    if x+width+2>1024:x=2;y+=row
    if y+height+2>1024:raise ValueError('Font atlas too small')
    draw.text((x-left,y-top),char,font=font,fill=(255,255,255,255),anchor='ls')
    glyphs.append(f'    {{{x},{y},{width},{height},{left},{top},{advance:.4f}f}},')
    x+=width+3
atlas.save(root/'resources/ui-font.png')
# ImageMagick exports BMP with a V4 alpha mask for SDL_LoadBMP.
import subprocess
subprocess.run(['magick',str(root/'resources/ui-font.png'),'-define','bmp:format=bmp4',str(root/'resources/ui-font.bmp')],check=True)
(root/'resources/ui-font.png').unlink()
(root/'src/ui-font.h').write_text('''// Generated by tools/bake_font.py from DejaVu Sans. See resources/FONT-LICENSE.txt.
#pragma once
struct FontGlyph {int x,y,w,h,left,top;float advance;};
inline constexpr FontGlyph font_glyphs[] = {
'''+ '\n'.join(glyphs)+'\n};\n')
(root/'resources/ui-font.json').write_text(json.dumps({'font':args.font.name,'sha256':hashlib.sha256(args.font.read_bytes()).hexdigest(),'pixel_size':88,'license':'FONT-LICENSE.txt'},indent=2)+'\n')
